-- CREATING THE DATAMODLE
USE meal_sharing;
-- MEAL TABLE
CREATE TABLE `meal`(
 `Id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
 `Title` VARCHAR(45)  NOT NULL,
 `Description` TEXT  NOT NULL,
 `Location` VARCHAR(75) NOT NULL,
 `When`  DATETIME NOT NULL,
 `Max_reservations` INT(10),
 `Price` DECIMAL(6,2),
 `Created_date` DATE NOT NULL
)
ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_UNICODE_CI;
-- RESERVATION TABLE
CREATE TABLE `reservation`(
`Id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`Number_of_guests` INT NOT NULL ,
`Meal_id`  INT NOT NULL , 
`Created_date`  DATE NOT NULL,
`Contact_phonenumber`  VARCHAR(45),
 `Contact_name` VARCHAR(45) NOT NULL,
`Contact_email`  VARCHAR(45) NOT NULL,
CONSTRAINT `fk_Meal_Id` FOREIGN KEY (`Meal_Id`)
        REFERENCES `Meal` (`Id`)
        ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_UNICODE_CI;

-- REVIEW TABLE
CREATE TABLE `review`(
`Id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
`Title` VARCHAR(45) NOT NULL,
`Description` TEXT NOT NULL ,
`Meal_Id` INT NOT NULL ,
`Stars` INT NOT NULL,
`Created_date` DATETIME NOT NULL,
CONSTRAINT `fk_Meal2_Id` FOREIGN KEY (`Meal_Id`)
        REFERENCES `Meal` (`Id`)
        ON DELETE CASCADE ON UPDATE CASCADE
)
ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE = UTF8MB4_UNICODE_CI;



